### ISSUE TITLE
2.x.x+ Backport

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#1]
## Overview
We need to phase out [this document](https://docs.google.com/spreadsheets/d/1ar7dTRooAzwKrZI4Xv3WNq0ZaVPiuTJd_1kRQ_QQsP0/edit?hl=en&forcehl=1#gid=162763738) and incorporate all relevant items we want to backport into Github in some form

Labels in use for this group and their definition

- ABIFILE - New feature which can provide abi_files for serialization/deserialization rather than relying on the blockchain.
- AMQP - Feature that existed in eosio that will not be ported to mandel
- APPBASE - appbase is a submodule that eosio/mandel uses. These are fixes/updates to that.
- AUDIT - Feature that existed in eosio that will not be ported to mandel
- BLOCKLOG - Either new development or improvements to an existing tool which tracks the history of blocks created in the blockchain
- BLOCKVAULT - Feature that existed in eosio that will not be ported to mandel
- BUGFIX - Fixes inside of eosio/mandel. This is in the actual code as opposed to tests, which are represented by TESTFIXES.
- CHAINBASE - fixes or updates to the blockchain database.
- CI - Continuous Integration.
- CLEOS - Command line EOS. This is the tool to provide commands to nodeos via the console.
- CMAKE - The build tool used for constructing eosio/mandel.
- DFUSE - a set of patches to DeepMind, which is the logging tool for eosio.
- DOCS - Update mostly or exclusively to documentation of eosio/mandel.
- EOSVM - Eosio Virtual machine
- FAILTRACE - A tool to trace transaction failures.
- FEATURE - New features added to the eosio blockchain/contracts. The only example of this is supporting std::array in smart contracts.
- IRREVBLOCKS - Support and fixes for irreversible blocks.
- KV - Key Value Database.
- LIGHTVAL - light validation and the associated test.
- LOGGING - Updates to the logging within eosio/mandel.
- LOGSPLIT - This is the support and fixes for block log splitting
- LSTESTS - Launcher Service tests.
- Nested CDT - CDT stands for Contract Development Toolchain.
- P2P - Peer to Peer.
- PACKEDTRX - Support to unpack transactions before signing.
- Perf - Performance improvements
- PRIVACY - Feature development on the feature-privacy development branch.
- PRUNE - blocklog pruning.
- REFLECTION - code relating to or testing FC_REFLECT.
- RESMON - The Resource Monitor Plugin which checks to see space left in the system and warns/errors if a limit is approached.
- REVBLOCKS - Support and fixes for reversible blocks.
- ROACTION - Read Only Action. Feature that existed in eosio that will not be ported to mandel
- ROCKSDB - Feature that existed in eosio that will not be ported to mandel
- Rodeos - Feature that existed in eosio that will not be ported to mandel
- SIGNEDTRX - Explicit ABI conversion of signed_transaction.
- SNAPSHOT - fixes or updates to snapshotting.
- SPAM - Junk PRs that community members made
- STATEHIST - This is the State History Plugin. We are in the process of porting it.
- SUBBILL - Subjective billing.
- TERMBLOCK - Option to terminate nodeos at a block.
- TESTFIXES - Assorted test fixes. Labels PRs that either only or mostly fix existing tests.
- TRACEAPI - Changes to the Trace Api Plugin.
- TRANSSPONS - Transaction Sponsorship. Work done on the transaction-sponsorship feature branch.
- TUTORIAL - fixes or updates to the bios_boot_tutorial.
- WASM - Web Assembly. This is the file type that is created when building contracts.
- ZAPHISTORY - Deleting state history plugin and integrating it into other existing plugins.
- ZIPKIN - Feature that existed in eosio that will not be ported to mandel

## Outstanding decisions
- Go-forward strategy for STATEHIST (state history) related items. Belief at this time is that it should just be one concerted effort instead of historical backports
- Go-forward strategy for KV (key value) related items. We may want to rethink KV strategy and agree on scope before proceeding
- Go-forward strategy with AMQP. This was originally identified as something that would not be moved over but we need further discussion on what sort of queueing support we plan to have before fully ruling this out.

**Comment by stephenpdeos** [comment]
Latest estimate from OCI was around 2-3 months of work remaining here down from 6 months

**Comment by heifner** [comment]
That is a VERY very rough order of magnitude "estimate".

**Comment by stephenpdeos** [comment]
No worries!

**Comment by stephenpdeos** [comment]
Other notes
- Additional considerations around any state history work being backported vs implementing moving forward
- Further discussion required around KV strategy before moving forward with backporting as well

**Comment by heifner** [comment]
We marked AMQP as NO. However, I've since had some second thoughts. I have heard of a number of projects using AMQP internally, there might actually be some desire to provide AMQP support. If we do bring it in it would be more of just pulling in the amqp_* plugin(s) from eosio/eos instead of back-porting any particular set of PRs.

We should determine if AMQP will be included in Mandel or not.

**Comment by stephenpdeos** [comment]
I've added an outstanding decisions section to the original description and will remove as resolved. AMQP item added.

**Comment by stephenpdeos** [comment]
Backports initiatives launched with 3.2 release
