### ISSUE TITLE
Prometheus Exporter Plugin

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/product#114]
Supporting Documentation:
- [Prometheus Plugin Architecture](https://github.com/orgs/eosnetworkfoundation/projects/7/views/35)

Related Tasks:
- [x] https://github.com/eosnetworkfoundation/mandel/issues/67
- [ ] https://github.com/AntelopeIO/leap/issues/108

See https://github.com/eosnetworkfoundation/product/pull/87

**Comment by bhazzard** [comment]
Items to include:

**Node Configs**

- Stuff from get_info

**Node Status**

- Unapplied transaction queue (Gauge)
    - number of transactions
    - byte size
    - speculative CPU time
- Blacklisted transactions (Counter)
    - by account
    - by key count
    - by contract count
- Subjective billing (Counter)
    - Number of accounts with subjective billing applied to them
- Scheduled transaction size (Gauge)
    - number of transactions
    - NOTE:
        - these are billed in RAM
        - relates to deferred transactions, which are deprecated
- Number of forks (Counter)
- Number of unapplied blocks (Counter)
- Number of dropped blocks (Counter)
- Number of transactions received by Peer (Counter)
    - Would include duplicates
    - Two parts: Peer could be P2P or an API
- Number of unique transactions received (Counter)
- Number of new connections (Gauge)
- Number of connections on wrong chain (Gauge)
- Uptime (Counter)
- CPU Usage by thread (Gauge)
- Disk space used by volume (blocks, ship, state, trace) (Gauge)
- Disk space available (Gauge)
- Current Block Number (Counter)

**Other Prometheus Exporter Requirements**

- Ability to expire metrics - clear on connection close

**Comment by matthewdarwin** [comment]
Can we please also add

- head_block_drift (gauge) `current time - block time`
- lib_drift (gauge) `current time - lib time`

**Comment by matthewdarwin** [comment]
Note "Disk space available" is also by volume.

**Comment by matthewdarwin** [comment]
For number of connections, consider inbound connections vs outbound connections.

- Can count the total number of connections.
- Can also count the number of failed outbound connections (failure due to duplicate should be ignored... eg when outbound connection and inbound connection match each other). Failure could be to DNS failure, Wrong Chain, etc...

**Comment by bhazzard** [comment]
Add # of http transactions in progress
