### ISSUE TITLE
Lighter Validation for Relays

### ISSUE THREAD

**Issue by bhazzard** [eosnetworkfoundation/product#127]
Related to #102 

To reduce latency of block propogation, relay blocks before fully validating or computing state if:

- Source can be trusted (valid signature from producer that should have produced for that block time)
- Block hasn't been tampered with (Merkle root of transactions is valid)

Nodes should fully validate the block before applying it to their blockchain.

Benefits:
- Reduce latency
- Could allow the creation of a new class of node (potentially an entirely new Antelope implementation for relay nodes)

Related tasks

- [x] https://github.com/AntelopeIO/leap/issues/568
- [x] https://github.com/AntelopeIO/leap/issues/525

**Comment by heifner** [comment]
Currently this requires a jump to the main thread to get the previous block from the fork database. It would be nice to not have to jump to the main thread to verify and propagate the block. One possibility is to make the forkdb thread-safe.
